services:
  aspire-dashboard:
    container_name: runjs-aspire
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS="true"

  postgres:
    container_name: runjs-pg
    image: postgres:17-alpine
    shm_size: 2g
    cpu_count: 2
    user: root
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"

  postgres-test:
    container_name: runjs-pg-test
    image: postgres:17-alpine
    restart: always
    user: root
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - 6543
    ports:
      - "6543:5432"
