// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RunJS;

#nullable disable

namespace EFExample.Migrations
{
    [DbContext(typeof(SecretsDatabase))]
    partial class SecretsDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RunJS.Secret", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_value");

                    b.HasKey("Id")
                        .HasName("pk_secrets");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_secrets_id");

                    b.ToTable("secrets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
